export const SBC_REQUIREMENTS = {
  "sbc.requirements.bronzePlayers": "Bronze Players Only",
  "sbc.requirements.challenge": "Challenge Requirements",
  "sbc.requirements.challenge.condensed": "Requirements",
  "sbc.requirements.clubs.scope0": "Clubs in Squad: Min. %1",
  "sbc.requirements.clubs.scope1": "Clubs in Squad: Max. %1",
  "sbc.requirements.clubs.scope2": "Clubs in Squad: Exactly %1",
  "sbc.requirements.combined.team.chemistry-points.scope0":
    "Min. %1 Squad Total Chemistry Points",
  "sbc.requirements.combined.team.chemistry-points.scope1":
    "Max. %1 Squad Total Chemistry Points",
  "sbc.requirements.combined.team.chemistry-points.scope2":
    "Exactly %1 Squad Total Chemistry Points",
  "sbc.requirements.combined.team.player-chemistry-points.scope0":
    "Min. %1 Chemistry Points on Each Player",
  "sbc.requirements.combined.team.player-chemistry-points.scope1":
    "Max. %1 Chemistry Points on Each Player",
  "sbc.requirements.combined.team.player-chemistry-points.scope2":
    "Exactly %1 Chemistry Points on Each Player",
  "sbc.requirements.firstowner.scope0": "First Owned Players: Min. %1",
  "sbc.requirements.firstowner.scope1": "First Owned Players: Max. %1",
  "sbc.requirements.firstowner.scope2": "First Owned Players: Exact %1",
  "sbc.requirements.fraction": "%1/%2",
  "sbc.requirements.goldPlayers": "Gold Players Only",
  "sbc.requirements.leagues.scope0": "Leagues in Squad: Min. %1",
  "sbc.requirements.leagues.scope1": "Leagues in Squad: Max. %1",
  "sbc.requirements.leagues.scope2": "Leagues in Squad: Exactly %1",
  "sbc.requirements.legend.scope0": "Icon Player: Min. %1",
  "sbc.requirements.legend.scope1": "Icon Player: Max. %1",
  "sbc.requirements.legend.scope2": "Icon Player: Exactly %1",
  "sbc.requirements.legends.scope0": "Icon Players: Min. %1",
  "sbc.requirements.legends.scope1": "Icon Players: Max. %1",
  "sbc.requirements.legends.scope2": "Icon Players: Exactly %1",
  "sbc.requirements.nations.scope0": "Nationalities in Squad: Min. %1",
  "sbc.requirements.nations.scope1": "Nationalities in Squad: Max. %1",
  "sbc.requirements.nations.scope2": "Nationalities in Squad: Exactly %1",
  "sbc.requirements.numplayers": "Number of Players in the Squad:",
  "sbc.requirements.player.scope0": "Player from the same %2: Min. %1",
  "sbc.requirements.player.scope0.val": "Min. %1 Player",
  "sbc.requirements.player.scope1": "Player from the same %2: Max. %1",
  "sbc.requirements.player.scope1.val": "Max. %1 Player",
  "sbc.requirements.player.scope2.val": "Exactly %1 Player",
  "sbc.requirements.playerQuality": "Player Quality:",
  "sbc.requirements.players.scope0": "Players from the same %2: Min. %1",
  "sbc.requirements.players.scope0.val": "Min. %1 Players",
  "sbc.requirements.players.scope1": "Players from the same %2: Max %1",
  "sbc.requirements.players.scope1.val": "Max. %1 Players",
  "sbc.requirements.players.scope2": "Players from the same %2: Exactly %1",
  "sbc.requirements.players.scope2.val": "Exactly %1 Players",
  "sbc.requirements.rare.scope0": "Min. %1 Players",
  "sbc.requirements.rare.scope1": "Max. %1 Players",
  "sbc.requirements.rare.scope2": "Exactly %1 Players",
  "sbc.requirements.rating.exact.scope0":
    "Players with exact OVR of %2: Min. %1",
  "sbc.requirements.rating.exact.scope1":
    "Players with exact OVR of %2: Max. %1",
  "sbc.requirements.rating.exact.scope2":
    "Players with exact OVR of %2: Exactly %1",
  "sbc.requirements.rating.exact.val": "Exact %1 OVR",
  "sbc.requirements.rating.max.scope0":
    "Players with maximum OVR of %2: Min. %1",
  "sbc.requirements.rating.max.scope1":
    "Players with maximum OVR of %2: Max. %1",
  "sbc.requirements.rating.max.scope2":
    "Players with maximum OVR of %2: Exactly %1",
  "sbc.requirements.rating.max.val": "Max. %1 OVR",
  "sbc.requirements.rating.min.scope0":
    "Players with minimum OVR of %2: Min. %1",
  "sbc.requirements.rating.min.scope1":
    "Players with minimum OVR of %2: Max. %1",
  "sbc.requirements.rating.min.scope2":
    "Players with minimum OVR of %2: Exactly %1",
  "sbc.requirements.rating.min.val": "Min. %1 OVR",
  "sbc.requirements.scope0": "Min.",
  "sbc.requirements.scope1": "Max.",
  "sbc.requirements.scope2": "Exactly",
  "sbc.requirements.silverPlayers": "Silver Players Only",
  "sbc.requirements.subType.club": "Club",
  "sbc.requirements.subType.league": "League",
  "sbc.requirements.subType.nation": "Nation",
  "sbc.requirements.team.chemistry-points.scope0": "Total Chemistry: Min. %1",
  "sbc.requirements.team.chemistry-points.scope1": "Total Chemistry: Max. %1",
  "sbc.requirements.team.chemistry-points.scope2":
    "Total Chemistry: Exactly %1",
  "sbc.requirements.team.chemistry.scope0": "Team Chemistry: Min. %1",
  "sbc.requirements.team.chemistry.scope1": "Team Chemistry: Max. %1",
  "sbc.requirements.team.chemistry.scope2": "Team Chemistry: Exactly %1",
  "sbc.requirements.team.player-chemistry-points.scope0":
    "Chemistry Points on Each Player: Min. %1",
  "sbc.requirements.team.player-chemistry-points.scope1":
    "Chemistry Points on Each Player: Max. %1",
  "sbc.requirements.team.player-chemistry-points.scope2":
    "Chemistry Points on Each Player: Exactly %1",
  "sbc.requirements.team.rating.scope0": "Team Rating: Min. %1",
  "sbc.requirements.team.rating.scope1": "Team Rating: Max. %1",
  "sbc.requirements.team.rating.scope2": "Team Rating: Exactly %1",
  "sbc.requirements.team.rating1to100.scope0": "Team Rating: Min. %1",
  "sbc.requirements.team.rating1to100.scope1": "Team Rating: Max. %1",
  "sbc.requirements.team.rating1to100.scope2": "Team Rating: Exactly %1",
  "sbc.requirements.tradable.scope0": "Tradable Players: Min. %1",
  "sbc.requirements.tradable.scope1": "Tradable Players: Max. %1",
  "sbc.requirements.tradable.scope2": "Tradable Players: Exact %1",
  "sbc.requirements.untradable.scope0": "Untradeable Players: Min. %1",
  "sbc.requirements.untradable.scope1": "Untradeable Players: Max. %1",
  "sbc.requirements.untradable.scope2": "Untradeable Players: Exact %1",
};

export const RARITY_GROUP = {
  Player_Group_11: "TOTW, TOTS or FUT Champions",
  Player_Group_12: "TOTW, TOTS or FUT Champions",
  Player_Group_18: "TOTW, TOTS",
  Player_Group_27: "Any TOTS or TOTW",
  Player_Group_28: "Any TOTS (Except UT Champions)",
  Player_Group_4: "Rare",
  Player_Group_5: "UCL Common or Rare",
  Player_Group_6: "UEFA Champions League Common or Rare",
  Player_Group_7: "RTTK",
  Player_Group_9: "Rare",
};

export const RARITY = {
  "item.raretype0": "Common",
  "item.raretype1": "Rare",
  "item.raretype10": "Pro Player",
  "item.raretype100": "Vintage",
  "item.raretype101": "Premium",
  "item.raretype102": "Ultimate",
  "item.raretype103": "UECL POTM",
  "item.raretype104": "Team of the Season Plus",
  "item.raretype105": "UECL Road to the Knockouts",
  "item.raretype106": "FUT VIP",
  "item.raretype107": "adidas NUMBERS UP",
  "item.raretype108": "FC Versus Ice",
  "item.raretype11": "Team of the Season",
  "item.raretype110": "SIGNATURE SIGNINGS",
  "item.raretype111": "Fantasy FC",
  "item.raretype113": "Special Item",
  "item.raretype114": "POTM SERIE A",
  "item.raretype115": "POTM EREDIVISIE",
  "item.raretype116": "FC Versus Fire",
  "item.raretype117": "Winter Wildcards",
  "item.raretype118": "WINTER WILDCARDS",
  "item.raretype119": "WILDCARD REWARD",
  "item.raretype12": "Icon",
  "item.raretype120": "WILDCARD TOKEN",
  "item.raretype121": "Standard",
  "item.raretype122": "Legendary",
  "item.raretype123": "UEFA EURO 2024 Player",
  "item.raretype124": "UCL Road to the Final",
  "item.raretype125": "UEL Road to the Final",
  "item.raretype126": "UECL Road to the Final",
  "item.raretype127": "TOTS Champions",
  "item.raretype128": "World Cup Player",
  "item.raretype129": "World Cup Icon",
  "item.raretype13": "Complete Founder Evolution",
  "item.raretype130": "FIFA WC Path To Glory",
  "item.raretype131": "World Cup Star",
  "item.raretype132": "World Cup Swap Token",
  "item.raretype133": "World Cup Hero",
  "item.raretype134": "FANTASY FUT",
  "item.raretype135": "Fantasy FC Hero",
  "item.raretype138": "World Cup Team of the Tournament",
  "item.raretype139": "Road to World Cup",
  "item.raretype14": "UWCL Team of the Group Stage",
  "item.raretype145": "World Cup Stories",
  "item.raretype146": "World Cup Phenoms",
  "item.raretype148": "World Cup Showdown",
  "item.raretype149": "Ultimate Birthday ICON",
  "item.raretype15": "In-Progress Founder Evolution",
  "item.raretype150": "Dynamic Duos",
  "item.raretype151": "Centurions",
  "item.raretype152": "FUT BIRTHDAY ICON",
  "item.raretype153": "Shapeshifters ICON",
  "item.raretype154": "FUTTIES Heroes",
  "item.raretype155": "TOTY ICON",
  "item.raretype156": "HISTORY MAKERS",
  "item.raretype157": "Thunderstruck ICON",
  "item.raretype158": "FIFA WORLD CUP™",
  "item.raretype159": "FUT Champions TOTS",
  "item.raretype16": "UT Winner",
  "item.raretype160": "GOLAZO Hero",
  "item.raretype161": "GOLAZO ICON",
  "item.raretype162": "FUT Birthday Swaps Token",
  "item.raretype163": "FUT Ballers",
  "item.raretype164": "Premium FUTTIES",
  "item.raretype165": "Premium Level Up",
  "item.raretype166": "PREMIUM SHAPESHIFTERS",
  "item.raretype167": "Level Up",
  "item.raretype168": "Centurions ICON",
  "item.raretype17": "Ultimate Team Champions Pro",
  "item.raretype170": "Future Stars ICON",
  "item.raretype171": "UEFA Heroes (Mens)",
  "item.raretype172": "UEFA Heroes (Womens)",
  "item.raretype18": "UT Champions",
  "item.raretype180": "UEFA Euro Path to Glory",
  "item.raretype181": "UEFA Euro Road to the Cup",
  "item.raretype182": "Nike",
  "item.raretype19": "Ultimate Team Champions",
  "item.raretype2": "Locked Items",
  "item.raretype20": "International Man of the Match",
  "item.raretype21": "Ones to Watch",
  "item.raretype22": "Trailblazers",
  "item.raretype23": "Radioactive EVO",
  "item.raretype24": "Squad Building Challenge",
  "item.raretype25": "End Of An Era",
  "item.raretype26": "Centurions Evo In-Progress",
  "item.raretype27": "Centurions Evo",
  "item.raretype28": "Triple Threat",
  "item.raretype3": "Team of the Week",
  "item.raretype30": "Ultimate Birthday",
  "item.raretype31": "UWCL Road to the Knockouts",
  "item.raretype32": "UWCL Road to the Final",
  "item.raretype33": "Thunderstruck",
  "item.raretype34": "FC Pro Live",
  "item.raretype35": "Winter Wildcards ICON",
  "item.raretype36": "Live Team of the Season",
  "item.raretype37": "Radioactive",
  "item.raretype38": "Special Item",
  "item.raretype39": "Special Item",
  "item.raretype4": "Match Winner",
  "item.raretype40": "Special Item",
  "item.raretype41": "Special Item",
  "item.raretype42": "POTM Bundesliga",
  "item.raretype43": "POTM Premier League",
  "item.raretype44": "Special Item",
  "item.raretype45": "UEFA Europa League POTM",
  "item.raretype46": "UEL Road to the Knockouts",
  "item.raretype47": "Winter Wildcards Evo",
  "item.raretype48": "Team of the Season Plus",
  "item.raretype49": "UEFA Champions League POTM",
  "item.raretype5": "Team of the Year",
  "item.raretype50": "UCL Road to the Knockouts",
  "item.raretype51": "Flashback Player",
  "item.raretype52": "CONMEBOL Sudamericana",
  "item.raretype53": "CONMEBOL Libertadores",
  "item.raretype54": "CONMEBOL Libertadores MOTM",
  "item.raretype55": "In-Progress Future Stars Evolution",
  "item.raretype56": "Select",
  "item.raretype57": "Showdown Plus",
  "item.raretype58": "SHOWDOWN",
  "item.raretype59": "CONMEBOL Sudamericana MOTM",
  "item.raretype6": "Record Breaker",
  "item.raretype60": "In-Progress Evolution",
  "item.raretype61": "Evolutions I",
  "item.raretype62": "Evolutions II",
  "item.raretype63": "Evolutions III",
  "item.raretype64": "TOTY Honourable Mentions",
  "item.raretype65": "TOTS Moments",
  "item.raretype66": "Future Stars Evo",
  "item.raretype67": "POTM MLS",
  "item.raretype68": "UEFA EUROPA LEAGUE TEAM OF THE TOURNAMENT",
  "item.raretype69": "UEL Team of the Group Stage",
  "item.raretype7": "Pundit Picks",
  "item.raretype70": "UEFA CHAMPIONS LEAGUE TEAM OF THE TOURNAMENT",
  "item.raretype71": "Future Stars",
  "item.raretype72": "UT Heroes",
  "item.raretype73": "Special Item",
  "item.raretype74": "Special Item",
  "item.raretype75": "NEXT LEVEL",
  "item.raretype76": "FGS SWAPS",
  "item.raretype77": "FGS SWAPS 2",
  "item.raretype78": "Special Item",
  "item.raretype79": "POTM Ligue 1",
  "item.raretype8": "Domestic Man of the Match",
  "item.raretype80": "FC Pro Open Jota",
  "item.raretype81": "Beats",
  "item.raretype82": "Triple Threat Heroes",
  "item.raretype83": "Special Item",
  "item.raretype85": "Ultimate Dynasties ICON",
  "item.raretype86": "POTM LALIGA EA SPORTS",
  "item.raretype87": "SQUAD FOUNDATIONS",
  "item.raretype870": "Special Item",
  "item.raretype88": "In-Progress Ultimate Birthday Evolution",
  "item.raretype89": "Ultimate Birthday Evo",
  "item.raretype9": "UT TBD",
  "item.raretype90": "Moments",
  "item.raretype91": "Storyline",
  "item.raretype92": "TOTS In-Progress EVO",
  "item.raretype93": "TOTS Champions Plus",
  "item.raretype94": "Special Item",
  "item.raretype95": "Ultimate Dynasties",
  "item.raretype95A": "HEADLINERS",
  "item.raretype96": "HEADLINERS STREAK",
  "item.raretype97": "Out of Position",
  "item.raretype98": "LEAGUE PLAYER",
  "item.raretype99": "Epic",
  "item.rraretype65": "TEAM OF THE SEASON MOMENTS",
  "item.rraretype67": "POTM MLS",
};
